apiVersion: v1
kind: Pod
metadata:
  name: pod-with-2-containers
spec:
  containers:
    - name: nginx1
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: tomcat-server
      image: tomcat:8
      ports:
        - containerPort: 8080